### PR TITLE
Add veda-data submodule, remove data folder + references to data folder

### PR DESCRIPTION
**Pull request by ividito**
**Summary:** 

Addresses [#246 - Separate ingestion definitions from infrastructure](https://github.com/NASA-IMPACT/veda-architecture/issues/246)

## Changes

* Added `veda-data` as a submodule. This repository will serve as a source of truth for ingestion inputs.
* Updated README and OPERATING docs
* removed data folder - this has been consolidated into `veda-data`

### CODE REVIEW

**Comment by ividito** [comment]
> Either way, would you mind if we brought it in after I figure out the various changes in https://github.com/NASA-IMPACT/veda-data-airflow/pull/82?

Sounds good to me. 

> I wonder if we couldn't just submit from a separate repo and avoid the data being in this repo at all.

I think it would be good to maintain the explicit link between the pipeline code and some accepted inputs for the pipeline, but if the submodule becomes annoying to maintain we can just link to the repo.

**Comment by ividito** [comment]
Rebased now that #82 is merged.

**Comment by gadomski** [comment]
> I think it would be good to maintain the explicit link between the pipeline code and some accepted inputs for the pipeline, but if the submodule becomes annoying to maintain we can just link to the repo.

My 2c: submodule maintenance is rarely worth it if it's not required. IMO documentation of the "this repo uses metadata stored in **veda-data**"" sort would be enough.

**Comment by slesaad** [comment]
Closing this in favor of https://github.com/NASA-IMPACT/veda-data-airflow/pull/110

**Pull request closed without merging**
